### ISSUE TITLE
run errors

### ISSUE THREAD

**Issue by luckywlj** [FilippoAiraldi/mpcrl-for-ramp-metering#1]
I configure the running environment according to the requirement file. When I run the train.py, there is an error as following:

 File "/home/xxx/mpcrl-for-ramp-metering-simulations/util/io.py", line 107, in <module>
    compression: None
TypeError: unsupported operand type(s) for |: 'NoneType' and '_LiteralGenericAlias'
 
It seems that the code line can not be solved. Could you help me to solve the problem?

**Comment by FilippoAiraldi** [comment]
Hi Luckywlj,

Is your python version correct?

**Comment by luckywlj** [comment]
yes, my python version is not correct.  Thank you for your answer.
