### ISSUE TITLE
Coordinated Control using Sym-Metanet

### ISSUE THREAD

**Issue by prajwalvinod** [FilippoAiraldi/mpcrl-for-ramp-metering#2]
Hey @FilippoAiraldi,

My name is Prajwal and I am a Masters student in Systems and Control at TU Delft. I am trying to use your code as a base for my traffic simulations for my thesis. I was wondering how one can implement the coordinated control that you described in the following link:

[https://github.com/FilippoAiraldi/sym-metanet/blob/dev/examples/coordinated_control_in_casadi.py](url)

with DDPG and SAC while making sure that both ramp metering and vsl actions are taken.

I have gone through both the repositories and I have understood how exactly you have achieved coordinated control with mpc; where you define both actions using a package. But should I want to achieve this using RL, I am having some trouble since I am not entirely sure how I can hardcode that 2 actions need to be taken in such an instance. 

I am adding my code which is a derivative of yours which I feel are relevant and hopefully you can give me some insight.

[files.zip](https://github.com/user-attachments/files/16445266/files.zip)

Additionally, is there a way to extract and plot data for the RL agents in a similar fashion to the LSTDQ plots ?

Looking forward to your reply.

Regards

Prajwal

**Comment by FilippoAiraldi** [comment]
Hi @prajwalvinod,

The environment that I defined [here](https://github.com/FilippoAiraldi/mpcrl-for-ramp-metering/blob/review1/metanet/highway_traffic_env.py) is compatible with stable-baselines-3, so it should not be difficult to play around with the hyperparameters of DDPG, or switch altogether to SAC. 

If you want to include also VSL as an action that the RL agent must take, then you have to expand the METANET network to include new links with VSL, and re-define the dynamics (and the environment that makes use of them) to accept not only the ramp metering action, but also the VSL actions as input from the RL agent. The rest should remain more or less the same.

Best of luck!

Filipppo

**Comment by prajwalvinod** [comment]
Hey @FilippoAiraldi,

When you say redefine the dynamics, where would I do that exactly ? Would it be in the `get_network` function or directly in the traffic environment ? 

I ask since in the traffic environment I see the shape defined as `na = self.na` followed by the line 
`self.action_space = Box( 0.0, 1.0 if control_O2_rate else np.inf, (na,), np.float64 )`
which was a bit confusing to me as it seems to imply that the environment can define the shape of the action space by itself so I assumed by adding the LinkWithVsl would automatically do this. 

If you could clarify this it would be helpful.

Regards

Prajwal

P.S. Its my first time using this package so I am a bit unfamiliar with it. Sorry for the inconvenience.
